export const initialResponse = {
  vmix: {
    version: "24.0.0.72",
    edition: "Pro",
    preset: "C:\\Users\\Administrator\\AppData\\Roaming\\last.vmix",
    inputs: {
      input: [
        {
          "#text": "box_beat_(125bpm_loop) (1080p).mp4",
          key: "bc03b28e-5609-43e3-9021-aa6ec9567a9a",
          number: "1",
          type: "Video",
          title: "box_beat_(125bpm_loop) (1080p).mp4",
          shortTitle: "box_beat_(125bpm_loop) (1080p).mp4",
          state: "Running",
          position: "10320",
          duration: "15423",
          loop: "True",
          muted: "False",
          volume: "49.78713",
          balance: "0",
          solo: "False",
          audiobusses: "M",
          meterF1: "0.5101767",
          meterF2: "0.5080402",
          gainDb: "0",
        },
        {
          "#text": "Browser www.youtube.com",
          key: "adb13004-4e2c-475c-b421-3fcc949e34e0",
          number: "2",
          type: "Browser",
          title: "Browser www.youtube.com",
          shortTitle: "Browser www.youtube.com",
          state: "Running",
          position: "0",
          duration: "0",
          loop: "False",
          muted: "True",
          volume: "100",
          balance: "0",
          solo: "False",
          audiobusses: "M",
          meterF1: "0",
          meterF2: "0",
          gainDb: "0",
        },
        {
          "#text": "Colour",
          key: "2651e76d-944e-42dd-bfe6-82df52773495",
          number: "3",
          type: "Colour",
          title: "Colour",
          shortTitle: "Colour",
          state: "Paused",
          position: "0",
          duration: "0",
          loop: "False",
        },
        {
          "#text": "Colour Bars",
          key: "a6e30522-fd21-4d46-a0b5-6376f1dace04",
          number: "4",
          type: "Colour",
          title: "Colour Bars",
          shortTitle: "Colour Bars",
          state: "Paused",
          position: "0",
          duration: "0",
          loop: "False",
        },
      ],
    },
    overlays: {
      overlay: [
        {
          number: "1",
        },
        {
          number: "2",
        },
        {
          number: "3",
        },
        {
          number: "4",
        },
        {
          number: "5",
        },
        {
          number: "6",
        },
        {
          number: "7",
        },
        {
          number: "8",
        },
      ],
    },
    preview: 2,
    active: 1,
    fadeToBlack: "False",
    transitions: {
      transition: [
        {
          number: "1",
          effect: "Fade",
          duration: "500",
        },
        {
          number: "2",
          effect: "Merge",
          duration: "1000",
        },
        {
          number: "3",
          effect: "Wipe",
          duration: "1000",
        },
        {
          number: "4",
          effect: "CubeZoom",
          duration: "1000",
        },
      ],
    },
    recording: "False",
    external: "False",
    streaming: "False",
    playList: "False",
    multiCorder: "False",
    fullscreen: "False",
    audio: {
      master: {
        volume: "100",
        muted: "False",
        meterF1: "0.5101767",
        meterF2: "0.5080402",
        headphonesVolume: "100",
      },
    },
    dynamic: {
      input1: "",
      input2: "",
      input3: "",
      input4: "",
      value1: "",
      value2: "",
      value3: "",
      value4: "",
    },
  },
};
